# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bbbbff3f8a5361ae8e48059d4f39cf565357c6a0d68c60c3d15420e93d3a2ca9f24e89197b719d51ce11ac927245e13c2be432c45e304fafe93bbec9617e836

test:
  secret_key_base: 308b762c02a3564e26bebfaffe4ba183f0d485749443711c4280e8c4d07148338f94b716d92269b5dd446e12dd448a9c2290af1a809a42edda46305bb915ad06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
